### DISCUSSION TITLE
HomeAssistant as a vpn client, and also a gateway

### DISCUSSION THREAD

**Discussion by zhujisheng** [hassio-addons/addon-wireguard#110] [Ideas]
Change the `config.json`, add `"host_network": "true"`, just like [this](https://github.com/zhujisheng/hassio-addons/blob/master/wireguard/config.json#L87)

my configuration:
```
server:
  host: something_you_like
  addresses:
    - 172.27.66.1
  dns: []
  private_key: myprivatekeyof172_27_66_1
  post_up: "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE; ip -4 route add x.x.x.x/32 via 192.168.1.1 dev wlan0"
  post_down: "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s 192.168.1.0/24 -j MASQUERADE; ip -4 route del x.x.x.x/32 via 192.168.1.1 dev wlan0"
peers:
  - name: hostwinds
    addresses:
      - 172.27.66.2
    allowed_ips: [0.0.0.0/1, 128.0.0.0/1]
    client_allowed_ips: []
    endpoint: 'x.x.x.x:51820'
    public_key: mypublickeyoftheserver
```
where the `x.x.x.x:51820` is the ip and vpn port of server, 192.168.1.0/24/gateway192.168.1.1 is the local network of the homeassistant.

Then, the HA connect to the vpn server; and if there's NAT rule set on server, you can set a local device's gateway as the IP of HomeAssistant to let it go out via the VPN.
