### DISCUSSION TITLE
Monitoring

### DISCUSSION THREAD

**Discussion by MisterRadish** [hassio-addons/addon-wireguard#234] [Q&A] [answered]
Thanks for all the hard work creating this addon. 

What is the best way to monitor access to Wireguard? 

I know I can view the logs to view the current state of the handshakes and data throughput but is it possible to use this information (events, states, log scrapping) in automation to support connection notifications for example? 

Thanks

Clive

**Comment by MisterRadish** [comment, marked as answer]
OK - re-read the documentation and spotted the WireGuard REST API!

What I wanted was an entity for each of my 3 peers (named peer1, peer2, peer3) for the last connection time. Here is my configuration.yaml entry using the RESTful sensor to make a single call to the WireGuard addon and then template sensors to split and format the data. 

```
sensor:
  - platform: rest
    resource: http://a0d7b954-wireguard
    name: "wireguard status"
    unique_id: wireguard_status
    value_template: "OK"
    json_attributes:
      - peer1
      - peer2
      - peer3

template:
  - sensor:
        name: "Wire Guard Peer1 Status"
        unique_id: wireguard_peer1
        state: "{{ as_datetime(state_attr('sensor.wireguard_status', 'peer1')['latest_handshake']).astimezone() }}"
  - sensor:
        name: "Wire Guard Peer2 Status"
        unique_id: wireguard_peer2
        state: "{{  as_datetime(state_attr('sensor.wireguard_status', 'peer2')['latest_handshake']).astimezone() }}"
  - sensor:
        name: "Wire Guard Peer3 Status"
        unique_id: wireguard_peer3
        state: "{{  as_datetime(state_attr('sensor.wireguard_status', 'peer3')['latest_handshake']).astimezone() }}"


```
