### DISCUSSION TITLE
No connection to LAN devices

### DISCUSSION THREAD

**Discussion by DigiLive** [hassio-addons/addon-wireguard#356] [Q&A]
I've configured the WG addon as show below and scanned to generated QR-code on my phone in the WG app.
The phone's WiFi is disabled.

If I'm not mistaken, I do get a connection with WG, but I can't connect to any of my devices in my home LAN.
Also, when connected to WG, it seems none of my apps will connect to the internet.

Changing `allowed_ips` and `client_allowed_ips` to `0.0.0.0/0` does allow access to the internet and https://www.whatsmyip.org/ does show the ip address of my ISP at home.
However, I'm still unable to access the devices in my home LAN.

FYI...
- My home LAN ip range is `192.168.178.0/24`.
- I tried to browse by ip to my router at `192.168.178.1`, HASS at `192.168.178.23:8123`, etc.

Any help help would be appreciated.
The goal is to be able to access the network "resources" which would be normally available and additionally to be able to access resources of my home LAN.

Server Configuration:

```yaml
host: xxx.duckdns.org
addresses:
  - 10.254.0.1/24
dns:
  - 172.30.32.1
```

Peers Configuration:

```yaml
- name: Test
  addresses:
    - 10.254.0.2/32
  allowed_ips:
    - 10.254.0.0/24
    - 192.168.178.0/24
  client_allowed_ips:
    - 10.254.0.0/24
    - 192.168.178.0/24
```
