### ISSUE TITLE
Unable to edit configuration of the addon

### ISSUE THREAD

**Issue by repssforjesus** [hassio-addons/addon-wireguard#104]
# Problem/Motivation

Not sure if it happened after new release of home assistant. But noticed that I am no longer able to add additional peers over the configuration. After saving it resets to the previous config.

Currently using WG addon: ```0.5.1```
```
hassos: "5.13"
homeassistant: 2021.4.1
```

Original configuration options:
```
server:
  host: mydns.duckdns.org
  addresses:
    - 10.10.10.1
  dns: []
peers:
  - name: myphone
    addresses:
      - 10.10.10.2
    allowed_ips: []
    client_allowed_ips: []
```

Unable to edit to:
```
server:
  host: mydns.duckdns.org
  addresses:
    - 10.10.10.1
  dns: []
peers:
  - name: myphone
    addresses:
      - 10.10.10.2
    allowed_ips: []
    client_allowed_ips: []
  - name: second_phone
    addresses:
      - 10.10.10.3
    allowed_ips: []
    client_allowed_ips: []
```

## Expected behavior

Edit configuration of the addon.

## Actual behavior

Configuration refreshes on saving with previous information.

## Steps to reproduce

-

## Proposed changes

-
