### ISSUE TITLE
vpn cannot access internet

### ISSUE THREAD

**Issue by gontxomde** [hassio-addons/addon-wireguard#139]
# Problem/Motivation

Followed the instructions to  create the VPN but the result is a VPN without internet connection when used.
I'm running HA Supervised running on top of Docker on a RPi with RaspBerry Pi OS Lite

## Expected behavior

I don't know if further configuration is needed in my router for this to work. What I expected is to get the QR code from the docker and being able to access the Internet with the IP provided by my ISP

## Actual behavior

I can connect to the VPN using the android app while connected to 4G. In the VPN logs I can see:

```
interface: wg0
  public key: zQ7Ta7O/sfeQ1VlCOFqfzJcBJQPb/7vO08tYc+jrly4=
  private key: (hidden)
  listening port: 51820
peer: 0JFEbcoyEe+Q2mWXaWFfZQCgyRcDN0Y+LW57GjiK8Wk=
  endpoint: 37.29.210.102:5627
  allowed ips: 172.27.66.2/32
  latest handshake: 6 minutes, 7 seconds ago
  transfer: 35.74 KiB received, 57.69 KiB sent
  persistent keepalive: every 25 seconds
```
The 'endpoint' matches the IP I have when I'm connected to 4G.
The latest handshake time increases monotonically

My phone has automatically no connection and I cannot reach the internet

## Steps to reproduce

My configuration file is as follows:

```yaml
server:
  host: xxxx.duckdns.org
  addresses:
    - 172.27.66.1
  dns:
    - 8.8.8.8
    - 8.8.4.4
peers:
  - name: gizaguirre
    addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
```

I don't really know if this problem is caused by the add-on or there might be any other piece that is the cause of this problem.
