### ISSUE TITLE
Addon works with setup peers but cannot ping/reach Hassio hosting the wireguard server addon

### ISSUE THREAD

**Issue by garret** [hassio-addons/addon-wireguard#184]
# Problem/Motivation

I have setup an internal vpn with some devices. Everything works perfectly. However, I cannot connect to the hassio device hosting the wireguard server addon. 

## Expected behavior

I would like to also connect to the hassio device (a raspberry pi 3B+) with the wireguard server addon.

## Actual behavior

Cannot connect to hassio device (a raspberry pi 3B+) with the wireguard server addon.

## Steps to reproduce

Cannot ping hassio via wireguard. 

## Proposed changes

Well, I guess now is obvious what I would like, that also the hassio hosting the wireguard addon/server can be reached by the vpn network.

**Comment by garret** [comment]
Issue still valid.

**Comment by mikewadsten** [comment]
@garret I have found that if you add these to your config's `server` block, you can reach HASS through Wireguard at `<server.addresses[0]>:8123`.

Just replace `W.X.Y.Z` with the LAN IP of your HASS instance. (There's probably a way to forward it directly to the host via the Docker internal-network, but whatever.)

```yaml
  post_up: >-
    iptables -A FORWARD -i %i -j ACCEPT;
    iptables -A FORWARD -o %i -j ACCEPT;
    iptables -t nat -A PREROUTING -p tcp --dport 8123 -j DNAT --to-destination W.X.Y.Z:8123;
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  post_down: >-
    iptables -D FORWARD -i %i -j ACCEPT;
    iptables -D FORWARD -o %i -j ACCEPT;
    iptables -D PREROUTING -p tcp --dport 8123 -j DNAT --to-destination W.X.Y.Z:8123;
    iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

The 3 other lines in each block (everything but the PREROUTING rule) are the default `PostUp` and `PostDown` values set up by the addon, [as seen here](https://github.com/hassio-addons/addon-wireguard/blob/c57f7e15e5eebb6eafd7376ea77f4ebfcf4172d4/wireguard/rootfs/etc/cont-init.d/config.sh#L102).

**Comment by garret** [comment]
@mikewadsten thank you very much for your help, really appreciate! However, I tried as you mention in your message but still cannot access hassio from inside wireguard vpn. I will share my config: 

```
peers:
  - name: Phone
    addresses:
      - 30.30.30.2
    allowed_ips: []
    client_allowed_ips:
      - 30.30.30.0/24
  - name: Laptop
    addresses:
      - 30.30.30.3
    allowed_ips: []
    client_allowed_ips:
      - 30.30.30.0/24

server:
  addresses:
    - 30.30.30.1
  dns:
    - 1.1.1.1
    - 1.0.0.1
  host: xyz.duckdns.org
  post_up: >-
    iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT;
    iptables -t nat -A PREROUTING -p tcp --dport 8123 -j DNAT --to-destination
    192.168.1.25:8123; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  post_down: >-
    iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT;
    iptables -D PREROUTING -p tcp --dport 8123 -j DNAT --to-destination
    192.168.1.25:8123; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```
(I tried to paste your lines but Hassio, after I save the wireguard config, messes up the lines of both `post_up` and `post_down` as you can see above. Don't know if that is the cause of my issue?!)

Phone (`30.30.30.2`) and laptop (`30.30.30.3`) can ping each other but there is no connection established when I try to access `30.30.30.1:8123` where I would expect to find the hassio homepage. 

In my home lan, the rapsberry pi 3b+ with hassio has a static IP of `192.168.1.25`. Thus, if inside my lan I type `192.168.1.25:8123` I can access hassio. 

Do you know what I am doing wrong?
