### ISSUE TITLE
Wireguard API is flapping up and down when connected

### ISSUE THREAD

**Issue by wernerhp** [hassio-addons/addon-wireguard#192]
# Problem/Motivation

Wireguard API keeps flapping (intermittent connected/disconnected)

## Expected behavior

When connected, the state should be reported consistently

## Actual behavior

When connected, the state flaps on and off
![image](https://user-images.githubusercontent.com/2578772/164896596-cfd8e41d-e63e-43d8-9492-76ac18ebb45e.png)

## Steps to reproduce

Setup Wireguard in HA with the API port 80
Configure a rest sensor as per Home Assistant documentation

Related issues
- https://github.com/hassio-addons/addon-wireguard/issues/65
- https://github.com/hassio-addons/addon-wireguard/issues/154

```
- platform: rest
  name: Wireguard
  resource: http://a0d7b954-wireguard
  json_attributes:
    - werner
  value_template: "OK"
  scan_interval: 120
  timeout: 30

- platform: template
  sensors:
    wireguard_werner:
      friendly_name: "Wireguard Werner"
      value_template: >-
        {% if state_attr('sensor.wireguard', 'werner').latest_handshake > ( as_timestamp(now()) ) -180 %}
          Connected
        {% else %}
          Disconnected
        {% endif %}
```

## Proposed changes

https://stackoverflow.com/a/22536458
An alternative server implemenation in go could be used instead of a bash server.
https://gitlab.com/wernerhp/wireguard-api/
