### ISSUE TITLE
can not visit ipv6 websites

### ISSUE THREAD

**Issue by thelittlefox** [hassio-addons/addon-wireguard#205]
Problem in this post was solved. 
We can visit ipv4 website now.
**But ipv6 website is unreachable using post#2 settings.**
domain names(ipv6) cannot be resolved to ip addresses .

when adding ipv6 address to server, wg0 interface does not turn up.
come up with error:
`RTNETLINK answers: Permission denied.`
it seems wireguard addons does not support ipv6 interface?

logs:
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-log-level.sh
> cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
> cont-init: info: running /etc/cont-init.d/config.sh
> cont-init: info: /etc/cont-init.d/config.sh exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun api (no readiness notification)
> services-up: info: copying legacy longrun status (no readiness notification)
> services-up: info: copying legacy longrun wireguard (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> [09:03:34] INFO: Starting WireGuard...
> [#] ip link add wg0 type wireguard
> [#] wg setconf wg0 /dev/fd/63
> [#] ip -4 address add 10.0.0.1/24 dev wg0
> [#] ip -6 address add 2001:22:2222::1/64 dev wg0
> **RTNETLINK answers: Permission denied**
> [#] ip link delete dev wg0

config:
```
peers:
  - addresses:
      - 10.0.0.2/32
    allowed_ips: []
    client_allowed_ips:
      - 0.0.0.0/0
    name: hassio
    pre_shared_key: secretcannotbeshown=
    public_key: secretcannotbeshown=
server:
  addresses:
    - 10.0.0.1/24
    - 2001:22:2222::1/64
  dns:
    - 8.8.8.8
  host: 192.168.1.59
  private_key: secretcannotbeshown=
  public_key: secretcannotbeshown=
```

below link may help:
https://bodhilinux.boards.net/thread/450/wireguard-rtnetlink-answers-permission-denied

> A solution that worked was editing /etc/sysctl.conf to add:
> 
> net.ipv6.conf.all.disable_ipv6 = 0
> net.ipv6.conf.default.disable_ipv6 = 0
> net.ipv6.conf.lo.disable_ipv6 = 0
