### ISSUE TITLE
Allow internet only, no access to internal network

### ISSUE THREAD

**Issue by madchap** [hassio-addons/addon-wireguard#211]
# Problem/Motivation

Probably more in need of help and not necessarily an issue in itself, apologies if that's the case.

I am trying to have certain peers only be able to connect and use internet, while forbidding access to internal networks. I don't want to only rely on the peer itself excluding private networks but want to have this controlled server side.

Simply setting `allowed_ips` to `192.168.10.6` in this example allows everything through, including access to internal networks and internet. So stuff works outside of this specific restricted configuration I'd want to have.

To do this, I am using the list provided at https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/ (second code example) in `allowed_ips` to allow internet and subtract internal networks.

However, everything is then blocked. it seems DNS then gets routed through the `wg0` interface and then fails. I also tried to leave the DNS configuration empty as the doc indicates "optional", but the configuration will not save so it seems to actually be required.

When putting DNS server 127.0.0.11 in the wg config, I would get:
```
root@a0d7b954-wireguard:/$ cat /etc/resolv.conf
# Generated by resolvconf                                                                                                     
nameserver 127.0.0.11                                                                                                         
                                                                        
root@a0d7b954-wireguard:/$ ping google.com                                                                                    
PING google.com (142.250.203.110): 56 data bytes                                                                              
ping: sendto: Destination address required  
```

Also, I am not really good at networking nor at wireguard :-)

My peer configuration
```
- name: iphone
  public_key: gsS................................
  addresses:
    - 192.168.30.6/32
  allowed_ips:
    - 192.168.30.6/32
    - 1.0.0.0/8
    - 2.0.0.0/7
    - 4.0.0.0/6
    - 8.0.0.0/7
    - 11.0.0.0/8
    - 12.0.0.0/6
    - 16.0.0.0/4
    - 32.0.0.0/3
    - 64.0.0.0/3
    - 96.0.0.0/4
    - 112.0.0.0/5
    - 120.0.0.0/6
    - 124.0.0.0/7
    - 126.0.0.0/8
    - 128.0.0.0/3
    - 160.0.0.0/5
    - 168.0.0.0/8
    - 169.0.0.0/9
    - 169.128.0.0/10
    - 169.192.0.0/11
    - 169.224.0.0/12
    - 169.240.0.0/13
    - 169.248.0.0/14
    - 169.252.0.0/15
    - 169.255.0.0/16
    - 170.0.0.0/7
    - 172.0.0.0/12
    - 172.32.0.0/11
    - 172.64.0.0/10
    - 172.128.0.0/9
    - 173.0.0.0/8
    - 174.0.0.0/7
    - 176.0.0.0/4
    - 192.0.0.0/9
    - 192.128.0.0/11
    - 192.160.0.0/13
    - 192.169.0.0/16
    - 192.170.0.0/15
    - 192.172.0.0/14
    - 192.176.0.0/12
    - 192.192.0.0/10
    - 193.0.0.0/8
    - 194.0.0.0/7
    - 196.0.0.0/6
    - 200.0.0.0/5
    - 208.0.0.0/4
    - 224.0.0.0/4
  client_allowed_ips:
    - 0.0.0.0/0
```

server config
```
addresses:
  - 192.168.30.1/24
dns:
  - 1.1.1.1
  - 1.0.0.1
host: vpn.domain.net
private_key: 8...............
public_key: s..................
```

The routes look then like this:
```
root@a0d7b954-wireguard:/$ ip route                                                                                 
default via 172.30.32.1 dev eth0
1.0.0.0/8 dev wg0 scope link                                                                                             
2.0.0.0/7 dev wg0 scope link                                                                                                  
4.0.0.0/6 dev wg0 scope link                                                                                                  
8.0.0.0/7 dev wg0 scope link                                                                                                  
11.0.0.0/8 dev wg0 scope link                                                                                                 
12.0.0.0/6 dev wg0 scope link                                                                                                 
16.0.0.0/4 dev wg0 scope link                                                                                                 
32.0.0.0/3 dev wg0 scope link                                                                                                 
64.0.0.0/3 dev wg0 scope link                                                                                                 
96.0.0.0/4 dev wg0 scope link                                                                                                 
112.0.0.0/5 dev wg0 scope link  
120.0.0.0/6 dev wg0 scope link  
124.0.0.0/7 dev wg0 scope link  
126.0.0.0/8 dev wg0 scope link  
128.0.0.0/3 dev wg0 scope link  
160.0.0.0/5 dev wg0 scope link  
168.0.0.0/8 dev wg0 scope link  
169.0.0.0/9 dev wg0 scope link  
169.128.0.0/10 dev wg0 scope link 
169.192.0.0/11 dev wg0 scope link 
169.224.0.0/12 dev wg0 scope link 
169.240.0.0/13 dev wg0 scope link 
169.248.0.0/14 dev wg0 scope link 
169.252.0.0/15 dev wg0 scope link 
169.255.0.0/16 dev wg0 scope link 
170.0.0.0/7 dev wg0 scope link  
172.0.0.0/12 dev wg0 scope link  
172.30.32.0/23 dev eth0 proto kernel scope link src 172.30.33.5  
172.32.0.0/11 dev wg0 scope link 
172.64.0.0/10 dev wg0 scope link 
172.128.0.0/9 dev wg0 scope link 
173.0.0.0/8 dev wg0 scope link  
174.0.0.0/7 dev wg0 scope link  
176.0.0.0/4 dev wg0 scope link  
192.0.0.0/9 dev wg0 scope link  
192.128.0.0/11 dev wg0 scope link 
192.160.0.0/13 dev wg0 scope link 
192.168.30.0/24 dev wg0 proto kernel scope link src 192.168.30.1 
192.169.0.0/16 dev wg0 scope link 
192.170.0.0/15 dev wg0 scope link 
192.172.0.0/14 dev wg0 scope link 
192.176.0.0/12 dev wg0 scope link 
192.192.0.0/10 dev wg0 scope link 
193.0.0.0/8 dev wg0 scope link 
194.0.0.0/7 dev wg0 scope link 
196.0.0.0/6 dev wg0 scope link 
200.0.0.0/5 dev wg0 scope link 
208.0.0.0/4 dev wg0 scope link 
224.0.0.0/4 dev wg0 scope link
```

## Expected behavior

The peer can connect and use any websites/public IPs, while being blocked from accessing internal networks.

## Actual behavior

Both internet and internal networks is blocked, apparently, because DNS no longer works.

## Steps to reproduce

Configure peer as shown above.

Any help very much appreciated :-) Thanks!
