### ISSUE TITLE
Peer connects but no traffic

### ISSUE THREAD

**Issue by santibur06** [hassio-addons/addon-wireguard#215]
# Problem/Motivation

VPN stopped working, can't really tell if it was after an update cause I had automatic updates enabled in the add-on configuration in HA.
It seems to be an issue related to iptables v1.8.8

## Actual behavior

Peer connects but there's no incoming/outgoing traffic, same behavior as when the server is down.

## Steps to reproduce

Here's my config file and the logs:
```
peers:
  - name: somename1
    addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
  - name: somename2
    addresses:
      - 172.27.66.3
    allowed_ips: []
    client_allowed_ips: []
  - name: somename3
    addresses:
      - 172.27.66.4
    allowed_ips: []
    client_allowed_ips: []
  - name: somename4
    addresses:
      - 172.27.66.5
    allowed_ips: []
    client_allowed_ips: []
server:
  addresses:
    - 172.27.66.1
  dns: []
  host: somehost.duckdns.org
```

Logs:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.7.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.6  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.5
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun api (no readiness notification)
services-up: info: copying legacy longrun status (no readiness notification)
services-up: info: copying legacy longrun wireguard (no readiness notification)
s6-rc: info: service legacy-services successfully started
[19:45:53] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables v1.8.8 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0
[19:46:23] INFO: Requesting current status from WireGuard...
[19:46:53] INFO: Requesting current status from WireGuard...
[19:47:23] INFO: Requesting current status from WireGuard...
[19:47:53] INFO: Requesting current status from WireGuard...
[19:48:23] INFO: Requesting current status from WireGuard...
```

**Comment by santibur06** [comment]
@frenck have you heard of anyone else having the same issue? I have the same issue with 3 installations

**Comment by nvm27** [comment]
I seem to have similar issue. For some time any client connecting via wireguard to my homeassistant instance is not able to access anything: HaOS host, hosts inside network and internet are inaccessible.
Connection to wireguard seem to be established fine from client. Tried with similar results from android and windows clients.
Not sure when exactly the issue started, but seem to be related to one of recent updates. I'm quite sure it was working in December.

My configuration:
```yaml
peers:
  - addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
    name: host1
  - addresses:
      - 172.27.66.3
    allowed_ips: []
    client_allowed_ips: []
    name: host2
server:
  addresses:
    - 172.27.66.1
  dns:
    - 172.30.32.1
  host: wg.somedomain.com
```

Logs:
```
6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.7.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.3
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun api (no readiness notification)
services-up: info: copying legacy longrun status (no readiness notification)
services-up: info: copying legacy longrun wireguard (no readiness notification)
s6-rc: info: service legacy-services successfully started
[16:32:05] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
[16:32:35] INFO: Requesting current status from WireGuard...
interface: wg0
  public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  private key: (hidden)
  listening port: 51820
peer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  allowed ips: 172.27.66.2/32
  persistent keepalive: every 25 seconds
peer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  allowed ips: 172.27.66.3/32
  persistent keepalive: every 25 seconds
[16:33:05] INFO: Requesting current status from WireGuard...
interface: wg0
  public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  private key: (hidden)
  listening port: 51820
peer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  allowed ips: 172.27.66.2/32
  persistent keepalive: every 25 seconds
```
