### ISSUE TITLE
HassOS Readonly Limitation

### ISSUE THREAD

**Issue by LanceMcCarthy** [hassio-addons/addon-wireguard#35]
# Problem/Motivation

IP forwarding doesn't work when running the add-on in HassOS (3.11) when you need LAN and internet.

## Expected behavior

Adding 192.168.1.0/0 to the allowed IPs list is needed for some client machine network adapter. 

## Actual behavior

No internet or local LAN access

State details
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.11  (amd64 / qemux86-64)
 Home Assistant version: 0.105.5
 Supervisor version: 201
-----------------------------------------------------------
```
## Steps to reproduce

1. Use the default Home Assistant installation option for VirtualBox ([the VHDX file here](https://www.home-assistant.io/hassio/installation/))
    - Be sure to choose Bridged network adapter for the VM
2. Install Wireguard add-on
3. Set the configuration to the defaults (or this one that has both internet and LAN access)

```yml
server:
  host: workinghostname.duckdns.org
  addresses:
    - 10.10.10.1/24
  dns:
    - 1.1.1.1
    - 1.0.0.1
peers:
  - name: MyPc
    publickey: <client public key>
    addresses:
      - 10.10.10.3/24
    allowed_ips: []
    client_allowed_ips:
      # All IPs allowed (default in add-on)
      - 0.0.0.0/0
      # LAN subnet defined for win10 adapters
      - 192.168.1.0/0
```

[Edit note] Removed irrelevant information from post.
