### ISSUE TITLE
Wireguard does not work behind Cloudflare

### ISSUE THREAD

**Issue by goodsale** [hassio-addons/addon-wireguard#355]
I have a Homeassistant server behind a router with a Vodafone SIM without a public address (CGNAT).

To reach Homeassistant I have my own domain xxxxx.com and Cloudflare.

My homeassistant is perfectly reachable from outside the domain xxxxx.com.

On this server I need to install a VPN that allows me to access my internal IPs from outside as if I were at home.

I tried to install WIREGUARD but if I open the VPN from my mobile phone I cannot reach my internal network.

It is not the first time that I install WIREGUARD because I have another Homeassistant server in another house where I have an external IP (no CGNAT) and duckdns, where the WIREGUARD VPN works without any problem.

I therefore believe that the problem is CLOUDFLARE and I would like to ask if there is a solution or an improvement that allows WIREGUARD to work under CLOUDFLARE.

Thanks

**Comment by goodsale** [comment]
I have a perfectly working cloudflare tunnel with domain mydomain.com
If I call the domain mydomain.com homeassistant responds by sending me my lovelace screen

I opened a subdomain in cloudflare called vpn.mydomain.com indicating in the cloudflare configuration the following:

```
external_hostname: mydomain.com
additional_hosts:
  - hostname: vpn.mydomain.com
    service: http://192.168.3.1
``` 

I don't know if this is correct in my network the IP 192.168.3.1 is the IP address of my WIREGUARD server.

Below is my WIREGUARD configuration:
```
host: vpn.mydomain.com
addresses:
  - 192.168.3.1
dns:
  - 192.168.2.1

- name: phone
  addresses:
    - 192.168.3.2
  allowed_ips: []
  client_allowed_ips:
    - 192.168.2.0/24
    - 192.168.3.0/24
``` 
The UDP port is open on my Router (FRITZBOX).

However, after scanning the QRCODE generated by WIREGUARD, I connect correctly but I don't have access from the device to my internal IP.

I would like to understand if this configuration for the two cloudflare and wireguard components is correct and if the subdomain is necessary.

Thanks!
