### ISSUE TITLE
How to use this addon as a client (Home) to my Office network?

### ISSUE THREAD

**Issue by netcookies** [hassio-addons/addon-wireguard#39]
I can connect the addon/server use my iphone or macbook, however I don't know how to config it as client to my Office network. Is there anything else I need to set up in hass.io? like ip_forwarding?

thks in adv.

```
server:
  host: {host}
  addresses:
    - 10.99.97.3
  private_key: {
  dns: []
peers:
  - name: office
    endpoint: 'xxxxxx'
    public_key: xxxxxxx
    addresses:
      - 10.99.97.1
    allowed_ips:
      - 10.99.97.1/32
      - 192.168.3.0/24
    client_allowed_ips: []
  - name: iphone
    public_key: xxxxx
    addresses:
      - 10.99.97.102
    allowed_ips: []
    client_allowed_ips: []
  - name: macbookpro
    public_key: xxxx
    addresses:
      - 10.99.97.103
    allowed_ips: []
    client_allowed_ips: []
log_level: info
```
