### ISSUE TITLE
Can't have more than 1 peers?

### ISSUE THREAD

**Issue by firestrife23** [hassio-addons/addon-wireguard#45]
When I attempt to save the configuration as:
```
server:
  host: xxxxxxxx
  addresses:
    - 10.10.10.1
  dns:
    - 172.30.32.1
peers:
  - name: dale
    addresses:
      - 10.10.10.2
    allowed_ips: []
    client_allowed_ips: []
  - name: dale_mobile
    addresses:
      - 10.10.10.3
    allowed_ips: []
    client_allowed_ips: []
```

it spew out error message: 

`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'server': {'host': 'xxxxxxxx', 'addresses': ['10.10.10.1'], 'dns': ['172.30.32.1']}, 'peers': [{'name': 'dale', 'addresses': ['10.10.10.2'], 'allowed_ips': [], 'client_allowed_ips': []}, {'name': 'dale_mobile', 'addresses': ['10.10.10.3'], 'allowed_ips': [], 'client_allowed_ips': []}]}`

However, if i changed it back to:

```
server:
  host: xxxxxxxx
  addresses:
    - 10.10.10.1
  dns:
    - 172.30.32.1
peers:
  - name: dale
    addresses:
      - 10.10.10.2
    allowed_ips: []
    client_allowed_ips: []
```
It gets saved without error message.

**Comment by firestrife23** [comment]
UPDATE: for some weird reason, it just doesn't like "dale_mobile" because of underscore, if I changed it  to dalemobile then it gets saved without error.

**Comment by 1337omega** [comment]
I just wanted to add a peer to my config and got the same error. It worked fine before.

`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'server': {'host': '*.*.*.*', 'addresses': ['172.27.66.1'], 'dns': '172.30.32.1'}, 'peers': [{'name': 'IphoneJuny', 'addresses': ['172.27.66.2'], 'allowed_ips': [], 'client_allowed_ips': []}, {'name': 'flappylappy', 'addresses': ['172.27.66.3'], 'allowed_ips': [], 'client_allowed_ips': []}, {'name': 'retropie', 'addresses': ['172.27.66.4'], 'allowed_ips': [], 'client_allowed_ips': []}, {'name': 'junydroid', 'addresses': ['172.27.66.5'], 'allowed_ips': [], 'client_allowed_ips': []}]}`

config before:

```
server:
  host: *.*.*.*
  addresses:
    - 172.27.66.1
  dns: 172.30.32.1
peers:
  - name: IphoneJuny
    addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
  - name: flappylappy
    addresses:
      - 172.27.66.3
    allowed_ips: []
    client_allowed_ips: []
  - name: IphoneMelis
    addresses:
      - 172.27.66.4
    allowed_ips: []
    client_allowed_ips: []
  - name: junydroid
    addresses:
      - 172.27.66.5
    allowed_ips: []
    client_allowed_ips: []
```

config after:

```
server:
  host: *.*.*.*
  addresses:
    - 172.27.66.1
  dns: 172.30.32.1
peers:
  - name: IphoneJuny
    addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
  - name: flappylappy
    addresses:
      - 172.27.66.3
    allowed_ips: []
    client_allowed_ips: []
  - name: IphoneMelis
    addresses:
      - 172.27.66.4
    allowed_ips: []
    client_allowed_ips: []
  - name: junydroid
    addresses:
      - 172.27.66.5
    allowed_ips: []
    client_allowed_ips: []
  - name: retropie
    addresses:
      - 172.27.66.6
    allowed_ips: []
    client_allowed_ips: []
```

i restored a snapshot from a week ago to see if Wireguard would come up but no. Everything was working fine. I use the VPN daily.
