### ISSUE TITLE
HA network connection dies short while after connecting to Wireguard VPN

### ISSUE THREAD

**Issue by Justus502** [hassio-addons/addon-wireguard#81]
# Problem/Motivation

My HomeAssistant becomes completely unresponsive via the network after a short while being connected with another device using the Wireguard VPN. The VPN functions for about a minute and then suddenly dies.
HA stays unconnected from the network until i pull the power plug and boot it again.

Happens on a RPI3B+ with the latest software installed. Connected via Ethernet cable and has a static IP address assigned in the supervisor.

What could be the issue here?
The logs show nothing until it disconnects and after the reboot no logs are to be found. 

## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4829
Installed Version | 1.11.3
Stage | running
Available Repositories | 751
Installed Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 19.03.13
disk_total | 109.3 GB
disk_used | 23.1 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), Log Viewer (0.9.1), Check Home Assistant configuration (3.6.0), File editor (5.2.0), Node-RED (8.1.2), Terminal & SSH (9.0.1), Let's Encrypt (4.11.0), AirCast (3.0.0), AdGuard Home (3.0.0), Home Assistant Google Drive Backup (0.103.1), RPC Shutdown (2.2), Mosquitto broker (5.1), Bitwarden RS (0.8.0), room-assistant (2.13.1), WireGuard (0.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 4
views | 31
mode | storage

</details>

## Expected behavior

Wireguard working without killing the Pi's network connection.

## Actual behavior

The Pi looses it's network connection and can't even be pinged any more. The system itself seems to be working when looking at the Pi's status LEDs and the HMDI-Output. It doesn't crash completely.

## Steps to reproduce

Raspberry Pi 3B+
Wireguard VPN Addon

The following configuration for the addon:
```
server:
  host: my.hostname.here
  addresses:
    - 172.27.66.1
  dns:
    - 172.30.32.1
peers:
  - name: iphone
    addresses:
      - 172.27.66.11
    allowed_ips: []
    client_allowed_ips: []
  - name: ipad
    addresses:
      - 172.27.66.12
    allowed_ips: []
    client_allowed_ips: []
  - name: laptop
    addresses:
      - 172.27.66.13
    allowed_ips: []
    client_allowed_ips: []
```
